export const UPDATE_BOARD_DATA = 'UPDATE_BOARD_DATA';
export const UPDATE_MODAL_STATUS = 'UPDATE_MODAL_STATUS';
export const UPDATE_CURRENT_CARD = 'UPDATE_CURRENT_CARD';
export const UPDATE_LIST_DATA = 'UPDATE_LIST_DATA';
export const UPDATE_CURRENT_LIST_NAME = 'UPDATE_CURRENT_LIST_NAME';
export const UPDATE_CURRENT_TASK_TYPE = 'UPDATE_CURRENT_TASK_TYPE';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';


export const UPDATE_DASHBOARD_DATA = 'UPDATE_DASHBOARD_DATA';
export const UPDATE_HEADER_NAME = 'UPDATE_HEADER_NAME';